StartupEvents.modifyCreativeTab('vinery:vinery', event => {
    event.remove('vinery:coarse_dirt_slab')
    event.remove('vinery:dirt_slab')
    event.remove('vinery:wandering_winemaker_spawn_egg')
    event.remove('vinery:dirt_path_slab')
    event.remove('vinery:grass_slab')
})

StartupEvents.modifyCreativeTab('biomeswevegone:biomes_weve_gone', event => {
    event.remove('biomeswevegone:windswept_sand')
    event.remove('biomeswevegone:windswept_sandstone')
    event.remove('biomeswevegone:windswept_sandstone_stairs')
    event.remove('biomeswevegone:windswept_sandstone_slab')
    event.remove('biomeswevegone:windswept_sandstone_wall')
    event.remove('biomeswevegone:chiseled_windswept_sandstone')
    event.remove('biomeswevegone:smooth_windswept_sandstone')
    event.remove('biomeswevegone:cut_windswept_sandstone')
    event.remove('biomeswevegone:smooth_windswept_sandstone_stairs')
    event.remove('biomeswevegone:smooth_windswept_sandstone_slab')
    event.remove('biomeswevegone:cut_windswept_sandstone_slab')
    event.remove('biomeswevegone:windswept_sandstone_pillar')
})

StartupEvents.modifyCreativeTab('mcwbyg:tab', event => {
    event.remove('mcwbyg:windswept_sandstone_grass_topped_wall')
    event.remove('mcwbyg:windswept_sandstone_pillar_wall')
    event.remove('mcwbyg:windswept_sandstone_railing_gate')
    event.remove('mcwbyg:railing_windswept_sandstone_wall')
    event.remove('mcwbyg:modern_windswept_sandstone_wall')
    event.remove('mcwbyg:windswept_sandstone_upper_steep_roof')
    event.remove('mcwbyg:windswept_sandstone_upper_lower_roof')
    event.remove('mcwbyg:windswept_sandstone_steep_roof')
    event.remove('mcwbyg:windswept_sandstone_lower_roof')
    event.remove('mcwbyg:windswept_sandstone_top_roof')
    event.remove('mcwbyg:windswept_sandstone_attic_roof')
    event.remove('mcwbyg:windswept_sandstone_roof')
    event.remove('mcwbyg:balustrade_windswept_sandstone_bridge')
    event.remove('mcwbyg:windswept_sandstone_bridge_stair')
    event.remove('mcwbyg:windswept_sandstone_bridge_pier')
    event.remove('mcwbyg:windswept_sandstone_bridge')
})

StartupEvents.modifyCreativeTab('adorn:items', event => {
    event.remove('adorn:copper_nugget')
})

StartupEvents.modifyCreativeTab('skd:blocks_and_items', event => {
    event.remove('skd:copper_nugget')
})

StartupEvents.modifyCreativeTab('stellaris:stellaris', event => {
    event.remove('stellaris:steel_ingot')
    event.remove('stellaris:steel_nugget')
    event.remove('stellaris:steel_block')
    event.remove('stellaris:steel_sword')
    event.remove('stellaris:steel_pickaxe')
    event.remove('stellaris:steel_axe')
    event.remove('stellaris:steel_shovel')
    event.remove('stellaris:steel_hoe')
})

StartupEvents.modifyCreativeTab('stellaris:stellaris_blocks', event => {
    event.remove('stellaris:steel_ore')
    event.remove('stellaris:deepslate_steel_ore')
    event.remove('stellaris:moon_steel_ore')
})

StartupEvents.modifyCreativeTab('minecraft:ingredients', event => {
    event.remove('adorn:copper_nugget')
})

StartupEvents.modifyCreativeTab('trafficcraft:trafficcrafttab', event => {
    event.remove('trafficcraft:iron_plate')
    event.remove('trafficcraft:hammer')
})

StartupEvents.modifyCreativeTab('create_connected:main', event => {
    event.remove('create_connected:copycat_stairs')
    event.remove('create_connected:copycat_slab')
    event.remove('create_connected:copycat_block')
    event.remove('create_connected:copycat_beam')
    event.remove('create_connected:copycat_vertical_step')
    event.remove('create_connected:copycat_fence')
    event.remove('create_connected:copycat_fence_gate')
    event.remove('create_connected:copycat_wall')
    event.remove('create_connected:copycat_board')
    event.remove('create_connected:copycat_box')
    event.remove('create_connected:copycat_catwalk')
})

StartupEvents.modifyCreativeTab('farmersdelight:farmersdelight', event => {
    event.remove('farmersdelight:rope')
})

StartupEvents.modifyCreativeTab('create_new_age:tab', event => {
    event.remove('create_new_age:magnetite_block')
    event.remove('create_new_age:redstone_magnet')
    event.remove('create_new_age:layered_magnet')
    event.remove('create_new_age:fluxuated_magnetite')
    event.remove('create_new_age:netherite_magnet')
    event.remove('create_new_age:basic_motor')
    event.remove('create_new_age:advanced_motor')
    event.remove('create_new_age:reinforced_motor')
    event.remove('create_new_age:basic_motor_extension')
    event.remove('create_new_age:advanced_motor_extension')
    event.remove('create_new_age:stirling_engine')
    event.remove('create_new_age:copper_wire_block')
    event.remove('create_new_age:overcharged_iron_wire_block')
    event.remove('create_new_age:overcharged_golden_wire_block')
    event.remove('create_new_age:overcharged_diamond_wire_block')
    event.remove('create_new_age:overcharged_diamond_wire')
    event.remove('create_new_age:overcharged_golden_wire')
    event.remove('create_new_age:overcharged_iron_wire')
    event.remove('create_new_age:copper_wire')
    event.remove('create_new_age:blank_circuit')
    event.remove('create_new_age:copper_circuit')
    event.remove('create_new_age:overcharged_iron_sheet')
    event.remove('create_new_age:overcharged_golden_sheet')
    event.remove('create_new_age:generator_coil')
    event.remove('create_new_age:electrical_connector')
    event.remove('create_new_age:carbon_brushes')
})
